import { afterAll, describe, expect, test } from "bun:test";
import { createHash } from "node:crypto";
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { discoverDesktopArtifacts, validateDesktopRuntimeManifest } from "../scripts/desktop-release-artifacts";
import { generateWindowsLatestJson, validateWindowsLatestJson } from "../scripts/desktop-latest-json";
import { assertDesktopVersionMetadata } from "../scripts/desktop-version-metadata";

const root = mkdtempSync(join(tmpdir(), "ocx-desktop-release-"));
afterAll(() => rmSync(root, { recursive: true, force: true }));

function writeManifest(path: string): void {
  const staged = join(root, "runtime", "package.json");
  mkdirSync(join(root, "runtime"), { recursive: true });
  writeFileSync(staged, "runtime-data\n", "utf8");
  const data = Buffer.from("runtime-data\n");
  writeFileSync(path, JSON.stringify({
    schemaVersion: 1,
    platform: "windows-x64",
    version: "2.7.31",
    files: [{ path: "runtime/package.json", size: data.length, sha256: createHash("sha256").update(data).digest("hex") }],
  }), "utf8");
}

describe("desktop release artifacts", () => {
  test("keeps package, Cargo, and Tauri version sources aligned", () => {
    const packageVersion = JSON.parse(readFileSync("package.json", "utf8")).version;
    expect(assertDesktopVersionMetadata(packageVersion)).toEqual({
      packageVersion,
      cargoVersion: packageVersion,
      tauriVersionSource: "../package.json",
    });
  });

  test("keeps the lockfile, explicit updater signature wiring, and CI-only exit hook", () => {
    const cargo = readFileSync("src-tauri/Cargo.toml", "utf8");
    const lock = readFileSync("src-tauri/Cargo.lock", "utf8");
    const main = readFileSync("src-tauri/src/main.rs", "utf8");
    const ci = readFileSync(".github/workflows/ci.yml", "utf8");
    const release = readFileSync(".github/workflows/release.yml", "utf8");
    const verifier = readFileSync("scripts/verify-windows-release-artifacts.ps1", "utf8");
    expect(lock).toContain("This file is automatically @generated by Cargo");
    expect(cargo).toContain("desktop-test-hook = []");
    expect(main).toContain("OCX_DESKTOP_TEST_EXIT_REQUEST");
    expect(ci).toContain("--features desktop-test-hook");
    expect(ci).toContain("verify-windows-release-artifacts.ps1");
    expect(release).toContain("verify-windows-release-artifacts.ps1");
    expect(release).toContain("dist\\desktop\\windows-x64\\**");
    expect(release).toContain("TAURI_WINDOWS_SIGNER_IDENTITY");
    expect(verifier).toContain("Get-AuthenticodeSignature");
    expect(verifier).toContain("signtool verify /pa /v");
    expect(release).toContain("opencodex-desktop.exe");
    expect(release).toContain("--pattern \"latest.json\"");
    expect(release).toContain("Do not replace them; publish a new release version.");
    expect(release.indexOf("-VerifyInstallerAuthenticode")).toBeLessThan(release.indexOf("Start-Process -FilePath (Join-Path $resumeDirectory $setup[0].name)"));
    expect(release).toContain("verify-windows-release-artifacts.ps1");
    expect(verifier).toContain("FromBase64String");
    expect(verifier).toMatch(/minisign -Vm .* -x .* -p/);
    expect(verifier.indexOf("minisign -Vm")).toBeLessThan(verifier.indexOf("if ($VerifyInstallerAuthenticode)"));
    expect(release).not.toContain("gh release upload \"$release_tag\" \"$installer\" \"$signature\" \"$checksum\"");
  });

  test("requires one NSIS setup executable, matching signature, and valid manifest", () => {
    const bundle = join(root, "bundle");
    const manifest = join(root, "manifest.json");
    mkdirSync(bundle, { recursive: true });
    writeManifest(manifest);
    const installer = join(bundle, "OpenCodex_2.7.31_x64-setup.exe");
    const application = join(root, "opencodex-desktop.exe");
    writeFileSync(installer, "installer", "utf8");
    writeFileSync(application, "application", "utf8");
    writeFileSync(`${installer}.sig`, "signed-updater-payload\n", "utf8");

    const artifacts = discoverDesktopArtifacts(bundle, manifest, application, "2.7.31");
    expect(artifacts.installerName).toBe("OpenCodex_2.7.31_x64-setup.exe");
    expect(artifacts.application).toBe(application);
    expect(artifacts.sha256).toMatch(/^[0-9a-f]{64}$/);
    expect(validateDesktopRuntimeManifest(manifest).files).toHaveLength(1);
    writeFileSync(join(root, "runtime", "package.json"), "tampered", "utf8");
    expect(() => validateDesktopRuntimeManifest(manifest)).toThrow("checksum does not match");
  });

  test("rejects a mutable or mismatched latest.json installer URL", () => {
    expect(() => generateWindowsLatestJson({
      version: "2.7.31",
      installerName: "OpenCodex_2.7.31_x64-setup.exe",
      installerUrl: "https://github.com/owner/repo/releases/latest/download/OpenCodex_2.7.31_x64-setup.exe",
      signature: "signed-updater-payload\n",
    })).toThrow("immutable HTTPS");

    const input = {
      version: "2.7.31",
      installerName: "OpenCodex_2.7.31_x64-setup.exe",
      installerUrl: "https://github.com/owner/repo/releases/download/v2.7.31/OpenCodex_2.7.31_x64-setup.exe",
      signature: "signed-updater-payload\n",
    };
    expect(generateWindowsLatestJson(input)).toEqual({
      version: "2.7.31",
      notes: "",
      platforms: {
        "windows-x86_64": {
          url: "https://github.com/owner/repo/releases/download/v2.7.31/OpenCodex_2.7.31_x64-setup.exe",
          signature: "signed-updater-payload\n",
        },
      },
    });
    expect(() => validateWindowsLatestJson({ version: "2.7.30", platforms: {} }, input)).toThrow("does not match");
    expect(() => validateWindowsLatestJson(generateWindowsLatestJson(input), input)).not.toThrow();
  });
});
